# -*- coding: utf-8 -*-
"""ML training pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjIcLgLZFGV8StEZtR8oh8xuuUF25tim
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

# --- Configuration ---
DATA_DIR = 'preprocessed_data'
X_FILE = 'X_data.npy'
Y_FILE = 'y_labels.npy'
MODEL_SAVE_PATH = 'ecg_bpm_classifier.h5'
NUM_CLASSES = 3
INPUT_SHAPE = (3600, 1) # 3600 samples (10s @ 360Hz), 1 channel

# --- 1. Load Data ---
print("Loading preprocessed data...")
X = np.load(f'{DATA_DIR}/{X_FILE}')
y = np.load(f'{DATA_DIR}/{Y_FILE}')

# Reshape X for CNN: (num_samples, timesteps, channels)
X = np.expand_dims(X, axis=-1)

# Convert labels to one-hot encoding
y_categorical = to_categorical(y, num_classes=NUM_CLASSES)

print(f"Data X shape: {X.shape}")
print(f"Data y shape: {y_categorical.shape}")

# --- 2. Split Data (80-10-10) ---
# First split: 80% train, 20% temp (validation + test)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y_categorical, test_size=0.2, random_state=42, stratify=y_categorical
)
# Second split: 50% of temp (10% total) for validation, 50% (10% total) for test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp
)

print(f"Train samples: {len(X_train)}")
print(f"Validation samples: {len(X_val)}")
print(f"Test samples: {len(X_test)}")

# --- 3. Build 1D-CNN Model ---
def build_model(input_shape, num_classes):
    model = Sequential([
        # C-M-C-M Block
        Conv1D(32, 5, activation='relu', input_shape=input_shape),
        MaxPooling1D(2),
        Conv1D(64, 5, activation='relu'),
        MaxPooling1D(2),

        # Classifier Head
        Flatten(),
        Dense(64, activation='relu'),
        Dropout(0.5), # Regularization to prevent overfitting
        Dense(num_classes, activation='softmax') # Softmax for multi-class
    ])
    return model

model = build_model(INPUT_SHAPE, NUM_CLASSES)

# Compile the model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# --- 4. Train Model ---
# Callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
model_checkpoint = ModelCheckpoint(MODEL_SAVE_PATH, monitor='val_accuracy', save_best_only=True)

print("\nStarting model training...")
history = model.fit(
    X_train, y_train,
    batch_size=32,
    epochs=50, # Will stop early if no improvement
    validation_data=(X_val, y_val),
    callbacks=[early_stopping, model_checkpoint]
)
print("Training complete.")

# --- 5. Evaluate Model ---
print("\nEvaluating model on test set...")
# Load the best model saved by ModelCheckpoint
model.load_weights(MODEL_SAVE_PATH)

test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")
print(f"Test Loss: {test_loss:.4f}")

# --- 6. Generate Reports ---
# Get predictions
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1) # Convert one-hot back to class index
y_test_labels = np.argmax(y_test, axis=1)

# Classification Report
print("\nClassification Report:")
class_names = ['0 (Bradycardia)', '1 (Normal)', '2 (Tachycardia)']
print(classification_report(y_test_labels, y_pred, target_names=class_names))

# Confusion Matrix
print("\nConfusion Matrix:")
cm = confusion_matrix(y_test_labels, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

# Plot Training History
print("Plotting training history...")
plt.figure(figsize=(12, 4))
# Plot Accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
# Plot Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.tight_layout()
plt.show()

print(f"Model saved to {MODEL_SAVE_PATH}")

from google.colab import drive
drive.mount('/content/drive')