# -*- coding: utf-8 -*-
"""preprocessed data model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1el-EbqrJWuO1jkoH95BWJk7-ssQKok8t
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. Data Loading and Preprocessing ---

# For this example, we'll use a pre-processed version of the MIT-BIH Arrhythmia Database
# available on Kaggle. This simplifies the data loading process.
# Download the dataset from: https://www.kaggle.com/shayanfazeli/heartbeat
# You will need two files: mitbih_train.csv and mitbih_test.csv

# Load the datasets
try:
    train_df = pd.read_csv('mitbih_train.csv', header=None)
    test_df = pd.read_csv('mitbih_test.csv', header=None)
except FileNotFoundError:
    print("Error: Make sure 'mitbih_train.csv' and 'mitbih_test.csv' are in the same directory as the script.")
    print("You can download them from: https://www.kaggle.com/shayanfazeli/heartbeat")
    exit()


# The last column is the label
X_train = train_df.iloc[:, :-1].values
y_train = train_df.iloc[:, -1].values

X_test = test_df.iloc[:, :-1].values
y_test = test_df.iloc[:, -1].values

# Ensure labels are integers
y_train = y_train.astype(int)
y_test = y_test.astype(int)


# The data is already segmented into heartbeats.
# The classes are:
# 0: Normal beat (N)
# 1: Supraventricular ectopic beat (S)
# 2: Ventricular ectopic beat (V)
# 3: Fusion beat (F)
# 4: Unknown beat (Q)

# Reshape the data for the 1D CNN
# The input shape for a 1D CNN is (num_samples, num_timesteps, num_features)
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

# NOTE: We removed the tf.keras.utils.to_categorical conversion.
# We will use sparse_categorical_crossentropy which works with integer labels directly.

# --- 2. CNN Model Architecture ---

model = Sequential()

# Convolutional Layer 1
model.add(Conv1D(filters=64, kernel_size=6, activation='relu',
                 input_shape=(X_train.shape[1], 1)))
model.add(MaxPooling1D(pool_size=3))
model.add(Dropout(0.3))

# Convolutional Layer 2
model.add(Conv1D(filters=128, kernel_size=6, activation='relu'))
model.add(MaxPooling1D(pool_size=3))
model.add(Dropout(0.3))

# Flatten the output to feed into the Dense layers
model.add(Flatten())

# Dense Layer 1
model.add(Dense(units=128, activation='relu'))
model.add(Dropout(0.3))

# Dense Layer 2
model.add(Dense(units=64, activation='relu'))
model.add(Dropout(0.3))

# Output Layer
model.add(Dense(units=5, activation='softmax')) # 5 classes

# Compile the model
# CHANGE 1: Switched loss function to 'sparse_categorical_crossentropy'
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Print the model summary
model.summary()


# --- 3. Model Training and Evaluation ---

# Train the model
history = model.fit(X_train, y_train,
                    epochs=20,
                    batch_size=128,
                    validation_data=(X_test, y_test))

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f"\nTest Accuracy: {accuracy*100:.2f}%")

# Make predictions
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# CHANGE 2: y_test is no longer one-hot encoded, so we can use it directly.
y_true = y_test

# Classification Report
print("\nClassification Report:")
print(classification_report(y_true, y_pred_classes, target_names=['N', 'S', 'V', 'F', 'Q']))

# Confusion Matrix
conf_matrix = confusion_matrix(y_true, y_pred_classes)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
            xticklabels=['N', 'S', 'V', 'F', 'Q'],
            yticklabels=['N', 'S', 'V', 'F', 'Q'])
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Plot training history
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()


# --- 4. Saving the Model ---

# Save the trained model for future use
model.save('ecg_arrhythmia_model.h5')
print("\nModel saved as ecg_arrhythmia_model.h5")

