# -*- coding: utf-8 -*-
"""Signal preprocessing code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNNl07ja7rv49LTiI7mlkJVuJUE7iEXb
"""

import wfdb
import numpy as np
import scipy.signal
from scipy.signal import find_peaks
import os

# --- Configuration ---
DATABASE_NAME = 'mitdb'  # MIT-BIH Arrhythmia Database
SAMPLING_RATE_MIT = 360  # The database's fixed sampling rate (360 Hz)
WINDOW_SECONDS = 10      # We'll use 10-second segments
WINDOW_SAMPLES = WINDOW_SECONDS * SAMPLING_RATE_MIT  # 3600 samples
OUTPUT_DIR = 'preprocessed_data'

# Select a good mix of records (as suggested in the prompt)
RECORDS = [
    '100', '101', '103', '105', '106', '108', '109', '111', '112',
    '113', '114', '115', '116', '117', '118', '119', '121', '122',
    '123', '124', '200', '201', '202', '203', '205', '207', '208',
    '209', '210', '212', '213', '214', '215', '217', '219', '220',
    '221', '222', '223', '228', '230', '231', '232', '233', '234'
]

# --- Utility Functions ---

def apply_bandpass_filter(signal, fs=SAMPLING_RATE_MIT, lowcut=0.5, highcut=40.0):
    """
    Applies a bandpass filter to the signal.
    """
    nyquist = 0.5 * fs
    low = lowcut / nyquist
    high = highcut / nyquist
    b, a = scipy.signal.butter(1, [low, high], btype='band')
    filtered_signal = scipy.signal.filtfilt(b, a, signal)
    return filtered_signal

def normalize_signal(signal):
    """
    Normalizes the signal to zero mean and unit variance (Z-score).
    """
    mean = np.mean(signal)
    std = np.std(signal)
    if std == 0:
        return signal - mean  # Avoid division by zero
    return (signal - mean) / std

def calculate_bpm_and_label(signal_segment, fs=SAMPLING_RATE_MIT):
    """
    Calculates BPM from a signal segment and returns a label.
    Label: 0 (<60), 1 (60-100), 2 (>100)
    """
    # Peak detection using scipy.signal.find_peaks
    # We set distance to 0.3s * fs to avoid detecting T-waves
    # (max BPM of 200)
    distance = int(0.3 * fs)
    # A simple height threshold
    height = np.mean(signal_segment) + 0.5 * np.std(signal_segment)

    peaks, _ = find_peaks(signal_segment, height=height, distance=distance)

    num_peaks = len(peaks)
    duration_seconds = len(signal_segment) / fs

    if duration_seconds == 0:
        return 1 # Default to 'Normal' if segment is empty

    bpm = (num_peaks / duration_seconds) * 60

    if bpm < 60:
        return 0  # Bradycardia
    elif bpm <= 100:
        return 1  # Normal
    else:
        return 2  # Tachycardia

# --- Main Preprocessing Pipeline ---

def preprocess_dataset():
    print(f"Starting preprocessing for {len(RECORDS)} records...")

    all_segments = []
    all_labels = []

    # Download the database
    print(f"Downloading database: {DATABASE_NAME}...")
    wfdb.dl_database(DATABASE_NAME, os.getcwd() + '/' + DATABASE_NAME, records=RECORDS)
    print("Download complete.")

    for record_name in RECORDS:
        print(f"Processing record: {record_name}")
        try:
            # Read the record
            record = wfdb.rdrecord(f'{DATABASE_NAME}/{record_name}', channels=[0])
            signal = record.p_signal[:, 0]

            # 1. Apply Filter
            filtered_signal = apply_bandpass_filter(signal)

            # 2. Segment into 10-second windows
            num_segments = len(filtered_signal) // WINDOW_SAMPLES
            for i in range(num_segments):
                start = i * WINDOW_SAMPLES
                end = start + WINDOW_SAMPLES
                segment = filtered_signal[start:end]

                # 3. Normalize the segment
                normalized_segment = normalize_signal(segment)

                # 4. Get label for the segment
                label = calculate_bpm_and_label(normalized_segment, SAMPLING_RATE_MIT)

                all_segments.append(normalized_segment)
                all_labels.append(label)

        except Exception as e:
            print(f"  Error processing record {record_name}: {e}")

    print(f"Preprocessing complete. Generated {len(all_segments)} segments.")

    # Convert to NumPy arrays
    X = np.array(all_segments)
    y = np.array(all_labels, dtype=int) # Cast to int

    # Create output directory if it doesn't exist
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    # Save the processed data
    np.save(os.path.join(OUTPUT_DIR, 'X_data.npy'), X)
    np.save(os.path.join(OUTPUT_DIR, 'y_labels.npy'), y)

    print(f"Data saved to '{OUTPUT_DIR}' directory.")
    print(f"Data shape (X): {X.shape}")
    print(f"Labels shape (y): {y.shape}")
    print(f"Label distribution: {np.bincount(y)}")

if __name__ == "__main__":
    preprocess_dataset()

pip install wfdb